### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by vincentcox** [TechxArtisanStudio/Openterface#9]
In terms of security (and thus reputation) it's required/good practice to redirect http to https.

<img width="628" alt="image" src="https://github.com/user-attachments/assets/5b387fab-bb9f-4593-a50a-08ea6b240aa5">

You can either implement [a redirect in the code](https://stackoverflow.com/a/50914931/9407192), or use Cloudflare free plan. When using cloudflare free plan, you set the [nameserver to cloudflare](https://developers.cloudflare.com/fundamentals/setup/manage-domains/add-site/) and then you can manage your DNS records there. You can also enable automatic https on the website which fixes this issue and also protects your website for future (D)dos attacks.

**Comment by kevinzjpeng** [comment]
Thanks for your informattion. 
We are using Github page for hosting, I just enforced to HTTPS, then all http request will redirect to https.
